[2018-06-04 07:06:09 +0300] [14702] [INFO] Starting gunicorn 19.8.1
[2018-06-04 07:06:09 +0300] [14702] [INFO] Listening at: http://0.0.0.0:5000 (14702)
[2018-06-04 07:06:09 +0300] [14702] [INFO] Using worker: sync
[2018-06-04 07:06:09 +0300] [14705] [INFO] Booting worker with pid: 14705
[2018-06-04 07:06:09 +0300] [14705] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/deryq/Desktop/moringa/django/sideprojects/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/deryq/Desktop/moringa/django/sideprojects/env/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/deryq/Desktop/moringa/django/sideprojects/env/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/deryq/Desktop/moringa/django/sideprojects/env/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/deryq/Desktop/moringa/django/sideprojects/env/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/deryq/Desktop/moringa/django/sideprojects/env/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/deryq/Desktop/moringa/django/sideprojects/env/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'helloapp'
[2018-06-04 07:06:09 +0300] [14705] [INFO] Worker exiting (pid: 14705)
[2018-06-04 07:06:09 +0300] [14702] [INFO] Shutting down: Master
[2018-06-04 07:06:09 +0300] [14702] [INFO] Reason: Worker failed to boot.
